sort exam1 | uniq -c | sort > sorted_exam1
sort exam2 | uniq -c | sort > sorted_exam2
sort exam3 | uniq -c | sort > sorted_exam3
sort exam4 | uniq -c | sort > sorted_exam4
sort exam5 | uniq -c | sort > sorted_exam5
sort exam6 | uniq -c | sort > sorted_exam6
sort exam7 | uniq -c | sort > sorted_exam7
sort exam8 | uniq -c | sort > sorted_exam8
sort exam9 | uniq -c | sort > sorted_exam9
sort exam10 | uniq -c | sort > sorted_exam10
sort exam11 | uniq -c | sort > sorted_exam11
sort exam12 | uniq -c | sort > sorted_exam12
sort exam13 | uniq -c | sort > sorted_exam13
sort exam14 | uniq -c | sort > sorted_exam14
sort exam15 | uniq -c | sort > sorted_exam15
sort exam16 | uniq -c | sort > sorted_exam16
sort exam17 | uniq -c | sort > sorted_exam17
sort exam18 | uniq -c | sort > sorted_exam18
sort exam19 | uniq -c | sort > sorted_exam19
sort exam20 | uniq -c | sort > sorted_exam20
