sort noExam1 | uniq -c | sort > sorted_noExam1
sort noExam2 | uniq -c | sort > sorted_noExam2
sort noExam3 | uniq -c | sort > sorted_noExam3
sort noExam4 | uniq -c | sort > sorted_noExam4
sort noExam5 | uniq -c | sort > sorted_noExam5
sort noExam6 | uniq -c | sort > sorted_noExam6
sort noExam7 | uniq -c | sort > sorted_noExam7
sort noExam8 | uniq -c | sort > sorted_noExam8
sort noExam9 | uniq -c | sort > sorted_noExam9
sort noExam10 | uniq -c | sort > sorted_noExam10
sort noExam11 | uniq -c | sort > sorted_noExam11
sort noExam12 | uniq -c | sort > sorted_noExam12
sort noExam13 | uniq -c | sort > sorted_noExam13
sort noExam14 | uniq -c | sort > sorted_noExam14
sort noExam15 | uniq -c | sort > sorted_noExam15
sort noExam16 | uniq -c | sort > sorted_noExam16
sort noExam17 | uniq -c | sort > sorted_noExam17
sort noExam18 | uniq -c | sort > sorted_noExam18
sort noExam19 | uniq -c | sort > sorted_noExam19
sort noExam20 | uniq -c | sort > sorted_noExam20
