sort examTotal1 | uniq -c | sort > sorted_total1
sort examTotal2 | uniq -c | sort > sorted_total2
sort examTotal3 | uniq -c | sort > sorted_total3
sort examTotal4 | uniq -c | sort > sorted_total4
sort examTotal5 | uniq -c | sort > sorted_total5
sort examTotal6 | uniq -c | sort > sorted_total6
sort examTotal7 | uniq -c | sort > sorted_total7
sort examTotal8 | uniq -c | sort > sorted_total8
sort examTotal9 | uniq -c | sort > sorted_total9
sort examTotal10 | uniq -c | sort > sorted_total10
sort examTotal11 | uniq -c | sort > sorted_total11
sort examTotal12 | uniq -c | sort > sorted_total12
sort examTotal13 | uniq -c | sort > sorted_total13
sort examTotal14 | uniq -c | sort > sorted_total14
sort examTotal15 | uniq -c | sort > sorted_total15
sort examTotal16 | uniq -c | sort > sorted_total16
sort examTotal17 | uniq -c | sort > sorted_total17
sort examTotal18 | uniq -c | sort > sorted_total18
sort examTotal19 | uniq -c | sort > sorted_total19
sort examTotal20 | uniq -c | sort > sorted_total20
